### ISSUE TITLE
Flag issues for older versions of Cabal / Use transformers-compat 0.4

### ISSUE THREAD

**Issue by bergmark** [haskell-compat/mtl-compat#1]
First of all, thanks for getting ExceptT adoption going with this package! It seems there is now less need for it to exist, but I'll leave that decision to you.

https://github.com/ekmett/lens/pull/523#issuecomment-74207812

With transformers-compat 0.4 the only thing this package can/needs to do is provide the `Control.Monad.Except` module. 

If mtl-compat is updated it should use the same trick as transformers-compat does, provide several versions instead of using flags, to prevent bugs in older Cabal versions.

It's also no longer necessary to use `mtl-compat`, to get a warning free build and get all the instances you  can `import Control.Monad.Trans.Except; import Control.Monad.Error.Class`.

**Comment by peti** [comment]
:+1: -- it would be great if `transformers-compat` 0.4.x would be supported, as we don't have older versions any more in NixOS and thus cannot build `mtl-compat` at all at the moment.

**Comment by RyanGlScott** [comment]
Wow, a lot happened while I was asleep. I'm extremely glad that `transformers-compat` has `mtl` instances now, since that relieves me of having the burden of maintaining them :).

As a result, I'm thinking of semi-deprecating `mt-compat`. It's functionally useless at this point, since `transformers-compat` backports all instances for `ExceptT` now. I suppose some might find a backported `Control.Monad.Except` useful, but I'll recommend `transformers-compat` in the package description.

Also, I wasn't aware of the versioning trick that `transformers-compat` uses—I'll update `mtl-compat` to do something similar, using `transformers-compat-0.4.

**Comment by RyanGlScott** [comment]
@peti: The build issues for NixOS should be fixed. Let me know if there are any issues.

Closed in b030c599cfe835edf69c04cd94bb6d28516b0b78.

**Comment by bergmark** [comment]
Awesome, thanks!
