### ISSUE TITLE
Unreachable `Control.Monad.Except`'s Hackage documentation

### ISSUE THREAD

**Issue by akhesaCaro** [haskell-compat/mtl-compat#4]
Hello,

When I am trying to reach the `Control.Monad.Except`'s documentation (https://hackage.haskell.org/package/mtl-compat-0.2.2/docs/Control-Monad-Except.html), I have this : 

![image](https://user-images.githubusercontent.com/17886931/108731301-b58f2480-752c-11eb-9459-4b289224259a.png)

Even the suggested link doesn't work : https://hackage.haskell.org/package/mtl-compat/docs/Control-Monad-Except.html

**Comment by RyanGlScott** [comment]
Good catch. Hackage usually renders the documentation for packages automatically when they get uploaded, but since `mtl-compat` only exposes `Control.Monad.Except` when building with old versions of `mtl`, there simply is no documentation to provide for newer versions. I've gone ahead and [manually uploaded Haddocks for `mtl-compat`](http://hackage.haskell.org/package/mtl-compat-0.2.2/docs/Control-Monad-Except.html) compiled with GHC 7.10.3, but do note that in general, the API is exactly the same as [what `mtl` exposes in its `Control.Monad.Except` module](http://hackage.haskell.org/package/mtl-2.2.2/docs/Control-Monad-Except.html).
